const http = require("http");
const fs = require("fs");
const path = require("path");
const { URL } = require("url");

const PORT = process.env.PORT || 8787;
const MANAGEMENT_KEY = process.env.OPENROUTER_MANAGEMENT_KEY || "";
const OPENROUTER_BASE = "https://openrouter.ai";
const PUBLIC_DIR = path.join(__dirname, "public");

function sendJson(res, status, data) { res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}); res.end(JSON.stringify(data)); }
function sendText(res,status,text,type="text/plain; charset=utf-8"){ res.writeHead(status,{"Content-Type":type}); res.end(text); }
async function readBody(req){ let body=""; for await(const chunk of req) body+=chunk; if(!body)return {}; return JSON.parse(body); }
function requireManagementKey(res){ if(!MANAGEMENT_KEY){sendJson(res,500,{error:"OPENROUTER_MANAGEMENT_KEY is not configured on the server."});return false;} return true; }
async function openRouter(pathname,options={}){ const response=await fetch(`${OPENROUTER_BASE}${pathname}`,{...options,headers:{Authorization:`Bearer ${MANAGEMENT_KEY}`,"Content-Type":"application/json",...(options.headers||{})}}); const text=await response.text(); let payload; try{payload=text?JSON.parse(text):{};}catch{payload={raw:text};} if(!response.ok){const err=new Error(payload?.error?.message||payload?.message||`OpenRouter ${response.status}`);err.status=response.status;err.payload=payload;throw err;} return payload; }
async function listAllKeys(includeDisabled=true,workspaceId=""){ const all=[]; for(let offset=0;offset<500;offset+=100){const qs=new URLSearchParams({include_disabled:includeDisabled?"true":"false",offset:String(offset)});if(workspaceId)qs.set("workspace_id",workspaceId);const payload=await openRouter(`/api/v1/keys?${qs}`);const rows=payload.data||[];all.push(...rows);if(rows.length<100)break;}return all; }
async function handleApi(req,res,url){ if(!requireManagementKey(res))return; try{
if(req.method==="GET"&&url.pathname==="/api/keys") return sendJson(res,200,{data:await listAllKeys(url.searchParams.get("include_disabled")!=="false",url.searchParams.get("workspace_id")||"")});
if(req.method==="POST"&&url.pathname==="/api/keys/bulk"){const body=await readBody(req);const students=Array.isArray(body.students)?body.students:[];if(!students.length||students.length>150)return sendJson(res,400,{error:"students must contain 1～150 rows."});const results=[];for(const student of students){const name=[student.studentId,student.name].filter(Boolean).join(" - ").trim();try{const payload={name:name||"Student",limit:body.limit===""||body.limit==null?null:Number(body.limit),limit_reset:body.limit_reset||null,include_byok_in_limit:Boolean(body.include_byok_in_limit)};if(body.expires_at)payload.expires_at=body.expires_at;if(body.workspace_id)payload.workspace_id=body.workspace_id;const created=await openRouter("/api/v1/keys",{method:"POST",body:JSON.stringify(payload)});results.push({ok:true,studentId:student.studentId||"",name:student.name||"",key:created.key||"",hash:created.data?.hash||"",limit:created.data?.limit??"",limitReset:created.data?.limit_reset||""});}catch(error){results.push({ok:false,studentId:student.studentId||"",name:student.name||"",error:error.message});}}return sendJson(res,200,{data:results});}
const match=url.pathname.match(/^\/api\/keys\/([a-f0-9]+)$/i);if(match&&req.method==="PATCH"){const body=await readBody(req);const allowed={};for(const key of ["name","disabled","include_byok_in_limit","limit","limit_reset"])if(Object.prototype.hasOwnProperty.call(body,key))allowed[key]=body[key];return sendJson(res,200,await openRouter(`/api/v1/keys/${match[1]}`,{method:"PATCH",body:JSON.stringify(allowed)}));}if(match&&req.method==="DELETE")return sendJson(res,200,await openRouter(`/api/v1/keys/${match[1]}`,{method:"DELETE",body:"{}"}));sendJson(res,404,{error:"API route not found"});}catch(error){sendJson(res,error.status||500,{error:error.message,details:error.payload||undefined});}}
function serveStatic(req,res,url){let rel=url.pathname==="/"?"index.html":url.pathname.replace(/^\/+/,"");rel=path.normalize(rel).replace(/^(\.\.[/\\])+/,"");const file=path.join(PUBLIC_DIR,rel);if(!file.startsWith(PUBLIC_DIR))return sendText(res,403,"Forbidden");fs.readFile(file,(err,data)=>{if(err)return sendText(res,404,"Not found");const type={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8"}[path.extname(file).toLowerCase()]||"application/octet-stream";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(data);});}
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith("/api/"))return handleApi(req,res,url);return serveStatic(req,res,url);}).listen(PORT,()=>console.log(`OpenRouter Key Manager: http://localhost:${PORT}`));
